name: ✨ Sugestão de funcionalidade
description: Proponha uma nova feature para o Forja
labels: [feature]
body:
  - type: markdown
    attributes:
      value: |
        Obrigado por contribuir com ideias! Por favor, preencha os campos abaixo para facilitar a avaliação da proposta.

  - type: textarea
    attributes:
      label: Qual é a funcionalidade desejada?
      description: Descreva o que você gostaria que fosse adicionado ao Forja.
      placeholder: |
        Seria interessante se o sistema permitisse...
    validations:
      required: true

  - type: textarea
    attributes:
      label: Justificativa
      description: Por que essa funcionalidade seria útil? Qual problema ela resolve?
      placeholder: |
        Isso ajudaria a...
    validations:
      required: true

  - type: textarea
    attributes:
      label: Alguma ideia de implementação?
      description: Caso já tenha pensado em como isso poderia ser feito, descreva aqui.
      placeholder: |
        Talvez usando a biblioteca X ou API Y...
    validations:
      required: false
