name: 🔧 Tarefa técnica
description: Criação de uma tarefa interna (refatoração, testes, etc.)
labels: [tech-debt]
body:
  - type: textarea
    id: escopo
    attributes:
      label: O que precisa ser feito?
  - type: textarea
    id: impacto
    attributes:
      label: Qual o impacto esperado?